---
# File:

- name: create ansible test group {{ aws_ansible_test_user }}
  iam_group:
    name: "{{ aws_ansible_test_user }}"
    managed_policy:
      - arn:aws:iam::aws:policy/AdministratorAccess
    state: present
    profile: "{{ aws_admin_user }}"

- name: create ansible test user {{ aws_ansible_test_user }} and keys
  iam:
    name: "{{ aws_ansible_test_user }}"
    iam_type: user
    state: present
    access_key_state: create
    groups: "{{ aws_ansible_test_user }}"
    profile: "{{ aws_admin_user }}"
  register: ansible_test_user_access_keys

- name: generate a 1 day security token
  sts_session_token:
    duration_seconds: 3600
  register: session_credentials
