---
# File:

- name: delete ansible test user {{ aws_ansible_test_user }}
  iam:
    name: "{{ aws_ansible_test_user }}"
    iam_type: user
    state: absent
    profile: "{{ aws_admin_user }}"

- name: delete ansible test group {{ aws_ansible_test_user }}
  iam_group:
    name: "{{ aws_ansible_test_user }}"
    state: absent
    profile: "{{ aws_admin_user }}"

- name: create ansible test group {{ aws_ansible_test_user }}
  iam_group:
    name: "{{ aws_ansible_test_user }}"
    managed_policy:
      - arn:aws:iam::aws:policy/AdministratorAccess
    state: present
    profile: "{{ aws_admin_user }}"

- name: create ansible test user {{ aws_ansible_test_user }} and keys
  iam:
    name: "{{ aws_ansible_test_user }}"
    iam_type: user
    state: present
    access_key_state: create
    groups: "{{ aws_ansible_test_user }}"
    profile: "{{ aws_admin_user }}"
  register: ansible_test_user_access_keys

- name: add test user to credentials file
  blockinfile:
    path: "{{ aws_credentials_file }}"
    insertafter: EOF
    block: |
      [{{ aws_ansible_test_user }}]
      aws_access_key_id={{ ansible_test_user_access_keys.user_meta.access_keys[0].access_key_id }}
      aws_secret_access_key={{ ansible_test_user_access_keys.user_meta.access_keys[0].secret_access_ke }}

- name: get aws ansible test user session token
  sts_session_token:
    profile: "{{ aws_ansible_test_user }}"
    region: "{{ aws_test_region }}"
  register: ansible_test_user_session_token
