---
# File:

- name: add test user to credentials file
  blockinfile:
    path: "{{ aws_credentials_file }}"
    insertafter: EOF
    marker: ""
    block: |
      [{{ aws_ansible_test_user }}]
      aws_access_key_id={{ ansible_test_user_access_keys.user_meta.access_keys[0].access_key_id }}
      aws_secret_access_key={{ ansible_test_user_access_keys.user_meta.access_keys[0].secret_access_key }}
