---
# File:

- name: add aws access key to bash profile
  lineinfile:
    path: "{{ bash_file_path }}"
    regexp: '^export AWS_ACCESS_KEY_ID=.*$'
    line: 'export AWS_ACCESS_KEY_ID={{ test_user_access_key_id }}'

- name: add aws secret key to bash profile
  lineinfile:
    path: "{{ bash_file_path }}"
    regexp: '^export AWS_SECRET_ACCESS_KEY=.*$'
    line: 'export AWS_SECRET_ACCESS_KEY={{ test_user_secret_access_key }}'

- name: add aws session token to bash profile
  lineinfile:
    path: "{{ bash_file_path }}"
    regexp: '^export AWS_SESSION_TOKEN=.*$'
    line: 'export AWS_SESSION_TOKEN={{ test_user_session_token }}'

- name: add aws region to bash profile
  lineinfile:
    path: "{{ bash_file_path }}"
    regexp: '^export AWS_REGION=.*$'
    line: 'export AWS_REGION={{ aws_test_region }}'
