---
# File:

- name: add aws access key to bash profile
  lineinfile:
    path: ~/ansible/test/integration/cloud-config-aws.yml
    regexp: '^AWS_ACCESS_KEY_ID:.*$'
    line: 'AWS_ACCESS_KEY_ID: {{ ansible_test_user_session_token.sts_creds.access_key }}'

- name: add aws secret key to bash profile
  lineinfile:
    path: ~/.bash_profile
    regexp: '^AWS_SECRET_ACCESS_KEY:.*$'
    line: 'AWS_SECRET_ACCESS_KEY: {{ ansible_test_user_session_token.sts_creds.secret_key }}'

- name: add aws session token to bash profile
  lineinfile:
    path: ~/.bash_profile
    regexp: '^AWS_SESSION_TOKEN:.*$'
    line: 'AWS_SESSION_TOKEN: {{ ansible_test_user_session_token.sts_creds.session_token }}'

- name: add aws region to bash profile
  lineinfile:
    path: ~/.bash_profile
    regexp: '^AWS_REGION:.*$'
    line: 'AWS_REGION: {{ aws_test_region }}'
