---
# File:

- name: get aws ansible test user session token
  shell: aws sts get-session-token --profile={{ aws_admin_user }} --output=json
  register: test_user_token_out

- set_fact:
    test_user_token: "{{ test_user_token_out|to_json }}"

- set_fact:
    test_user_access_key_id: "{{ test_user_token.Credentials.AccessKeyId }}"

- set_fact:
    test_user_secret_access_key: "{{ test_user_token.Credentials.SecretAccessKey }}"

- set_fact:
    test_user_session_token: "{{ test_user_token.Credentials.SessionToken }}"
