---
# File:

- name: clone ansible repo of user {{ github_username }}
  git:
    repo: "https://github.com/{{ github_username }}/ansible"
    dest: ~/ansible

- name: add remote upstream of ansible
  shell: git remote add upstream https://github.com/ansible/ansible
  args:
    chdir: ~/ansible
  ignore_errors: yes

- name: sync local repo with upstream
  shell: git pull upstream devel
  args:
    chdir: ~/ansible
