---
# File:

- name: install selinux dependency
  package:
    name: libselinux-python
    state: latest

- name: install ntp
  package:
    name: ntp
    state: latest

- name: set date
  shell: ntpd -gq
  become: yes

- name: install git
  package:
    name: git
    state: latest

- name: install docker
  package:
    name: docker
    state: latest

- name: create docker group
  group:
    name: docker
    state: present

- name: add user to docker group
  user:
    name: "{{ ansible_user_id }}"
    groups: docker

- name: start docker service at boot
  service:
    name: docker
    enabled: yes

- name: restart docker service
  service:
    name: docker
    state: restarted

- name: install epel-release branch
  package:
    name: epel-release
    state: present

- name: install python-pip
  package:
    name: python-pip
    state: present

- name: install vim
  package:
    name: vim
    state: latest

- name: install botocore
  pip:
    name: botocore

- name: install boto3
  pip:
    name: boto3

- name: install boto
  pip:
    name: boto

- name: install awscli
  pip:
    name: awscli
